export const DrugList = [
  {
    drugName: "paracetamol",
    minDoseMgPerKg: 40,
    maxDoseMgPerKg: 60,
    maxDailyDose: 4000,
    freq: "QDS",
    ageRange: [0],
    notes: "Avoid use under 3 months, neonatal pyrexia may warrant referral",
  },
  {
    drugName: "ibuprofen",
    minDoseMgPerKg: 15,
    maxDoseMgPerKg: 30,
    maxDailyDose: 1200,
    freq: "TDS",
    ageRange: [0],
    notes: ">6mths >5kg",
  },
  {
    drugName: "chlorpheniramine",
    minDoseMgPerKg: [0.3, 0.3, 0.3],
    maxDoseMgPerKg: [0.3, 0.3, 0.3],
    maxDailyDose: [2, 2, 4],
    freq: ["TDS", "TDS", "TDS"],
    ageRange: [1, 2, 6],
    notes: "",
  },
  {
    drugName: "cetirizine",
    minDoseMgPerKg: [0.5, 0.5, 0.5],
    maxDoseMgPerKg: [0.5, 0.5, 0.5],
    maxDailyDose: [2.5, 5, 10],
    freq: ["OD", "BD", "BD"],
    ageRange: [0.5, 1, 6],
    notes: "",
  },
  {
    drugName: "amoxicillin",
    minDoseMgPerKg: [20, 25],
    maxDoseMgPerKg: [30, 50],
    maxDailyDose: [4000, 4000],
    freq: ["BD", "TDS"],
    ageRange: [0, 1 / 12],
    notes: ">=2mo: Severe infection e.g. Otitis Media up to 90mg/kg/day q8h",
  },
  {
    drugName: "prometazine",
    minDoseMgPerKg: 0.75,
    maxDoseMgPerKg: 1.5,
    maxDailyDose: 75,
    freq: "TDS",
    ageRange: [2],
    notes: "Test5",
  },
];
